version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=corposup
      - DB_USERNAME=root
      - DB_PASSWORD=2997924581668719
    volumes:
      - ./backend/storage:/var/www/storage

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: corposup
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
