version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontendd:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
